### ISSUE TITLE
dylp build failure on OS X Apple Silicon 

### ISSUE THREAD

**Issue by mandeluna** [coin-or-tools/homebrew-coinor#80]
```
Already downloaded: /Users/steve/Library/Caches/Homebrew/downloads/a59ec445aa03612060969fa16d2fbd67876499140d9648a2895054ea3cbb7608--DyLP-releases-1.10.4.tar.gz
==> Installing dylp from coin-or-tools/coinor
==> ./configure --prefix=/opt/homebrew/Cellar/dylp/1.10.4_1 --datadir=/opt/homebrew/Cellar/dylp/1.10.4_1/shar
==> make
Last 15 lines from /Users/steve/Library/Logs/Homebrew/dylp/02.make:
mkdir .libs/libDylp.lax
rm -fr .libs/libDylp.lax/libDylpStdLib.a
mkdir .libs/libDylp.lax/libDylpStdLib.a
Extracting /private/tmp/dylp-20220215-49959-jtxmak/DyLP-releases-1.10.4/DyLP/src/Dylp/../DylpStdLib/.libs/libDylpStdLib.a
(cd .libs/libDylp.lax/libDylpStdLib.a && ar x /private/tmp/dylp-20220215-49959-jtxmak/DyLP-releases-1.10.4/DyLP/src/Dylp/../DylpStdLib/.libs/libDylpStdLib.a)
clang -dynamiclib -single_module  -o .libs/libDylp.1.9.4.dylib  .libs/dy_consys_io.o .libs/dy_consys_mathutils.o .libs/dy_consys_scaling.o .libs/dy_consys_utils.o .libs/dy_basis.o .libs/dy_bound.o .libs/dy_cmdint.o .libs/dy_coldstart.o .libs/dy_conmgmt.o .libs/dy_dual.o .libs/dy_dualmultipivot.o .libs/dy_dualpivot.o .libs/dy_duenna.o .libs/dy_force.o .libs/dy_hotstart.o .libs/dylp.o .libs/dylp_io.o .libs/dylp_utils.o .libs/dy_options.o .libs/dy_penalty.o .libs/dy_pivreject.o .libs/dy_primal.o .libs/dy_primalmultipivot.o .libs/dy_primalpivot.o .libs/dy_rays.o .libs/dy_scaling.o .libs/dy_setup.o .libs/dy_solutions.o .libs/dy_statistics.o .libs/dy_tableau.o .libs/dy_varmgmt.o .libs/dy_warmstart.o .libs/glpinv.o .libs/glplib1.o .libs/glplib2.o .libs/glplib3.o .libs/glplib4.o .libs/glpluf.o .libs/dy_vector_utils.o  .libs/libDylp.lax/libDylpStdLib.a/dylib_bnfrdr.o .libs/libDylp.lax/libDylpStdLib.a/dylib_strrtns.o .libs/libDylp.lax/libDylpStdLib.a/dylib_errs.o .libs/libDylp.lax/libDylpStdLib.a/dylib_bnfrdrio.o .libs/libDylp.lax/libDylpStdLib.a/dylib_littab.o .libs/libDylp.lax/libDylpStdLib.a/dylib_binsrch.o .libs/libDylp.lax/libDylpStdLib.a/dylib_hash.o .libs/libDylp.lax/libDylpStdLib.a/dylib_io.o   -lm  -install_name  /opt/homebrew/Cellar/dylp/1.10.4_1/lib/libDylp.1.dylib -compatibility_version 11 -current_version 11.4
Undefined symbols for architecture arm64:
  "_unavailable", referenced from:
      _consys_create in dy_consys_utils.o
      _dy_ctlopt in dy_options.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libDylp.la] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1
```

**Comment by tkralphs** [comment]
Hmm, not sure exactly what's going on here. @LouHafer do you have any theory? This recipe is working for other platforms, including intel-based OS X. Seems to be something going on with M1-based OS X.

**Comment by LouHafer** [comment]
@mandeluna, @tkralphs, I have no access to this platform, so this is just a guess: The configuration macro m4/AC_DYLP_FIND_ISFINITE is failing. If that's the case, there should be a warning when configure runs that says 'Cannot find a C function to check if an IEEE floating point value is finite. There is no hope of building dylp on this system.' and an information message that says 'Using unavailable as isfinite.'  The macro checks for finite, _finite, and isfinite. It needs another stanza that'll find the correct name for M1 arm64. You can confirm this by looking at the file DylpStdLib/config.h in the build directory. If you see `#define DYLP_ISFINITE unavailable`, this is the problem. To confirm, simply edit this file to supply the correct name and try a rebuild without configuring. You'll also need to check DYLP_ISNAN, immediately below. I have no access to an Apple M1 system, so I can't help with guessing the correct function name.

Peripherally related to the above, building dylp with -fvisibility=hidden breaks all sorts of things. I'm working on that now as I try to drag dylp up to the current build framework. ThirdParty/Glpk has the same problem, but not really fixable on our side.

**Comment by tkralphs** [comment]
Your guess makes sense since we ran into a similar failure in a similar test on the same platform in CoinUtils. If you look at recent commits there, you should see a link to an issue where this is discussed. I'm not at my computer now but will give more details later.

**Comment by mandeluna** [comment]
Thanks gents, looks like the same as Issue #62 -- I'm working through the steps, not super familiar with homebrew recipes, but I will close this issue once I've confirmed.

**Comment by LouHafer** [comment]
@mandeluna, @tkralphs Found it (#62). C shouldn't have the overload problem, but looking at dylp's configure.ac the test is running in the C++ context and that might well be causing the failure. OsiDylp uses CoinFinite.hpp and should pick up the fixes there. Might be that the best solution for the C part of dylp would be to guard the C portions of dylp's configure with  AC_LANG_PUSH(C) / AC_LANG_POP(C).  @mandeluna, if edting DylpStdLib/config.h per above works, let us know, please.

**Comment by mandeluna** [comment]
I'm not familiar with autoconf but I tried wrapping the macro as you suggested and it didn't fix the problem. Replacing the reference to "unavailable" with "isfinite" allowed the build to complete. On x86-64 Linux it looks like the script is generating a call to "finite", which doesn't seem to be available on this version of OS X. This issue may be due to an OS change rather than a different architecture.

**Comment by LouHafer** [comment]
@mandeluna, after changing configure.ac or Makefile.am you need to run the run_autotools script from coin-or-tools/BuildTools in order to actually update the configure script and Makefile.in. Might well be more than you want to get into if you don't regularly work with autotools. Knowing that `isfinite` works definitely narrows down the problem. At the moment I have dylp spread out in pieces on the floor as I try to update it to work with the current Coin build architecture. There will be truly radical change to coin-or/dylp within a week or so. I'll try to make some time to patch dylp's configure.ac. I'll ping you when I've done it.

**Comment by LouHafer** [comment]
@mandeluna, @tkralphs, I've pushed an updated dylp to coin-or/Dylp/master. I was nearly done with the first cut at the update when this issue arose. I'm hoping changes to configure.ac (specifically, running the check for isfinite as C rather than C++, so overloads don't kick in) will fix this issue. @tkralphs, this version passes the workflow unix & macos checks with visibility=hidden. @mandeluna, depending on just what you're doing with dylp, the changes may break your code --- I've renamed some symbols (added a dy_ prefix) and added proper support for symbol visibility hidden by default. The latter means that some symbols that used to be exported may not be exported now. See comments in dylp.h about DYLPLIB_EXPORT. If you're working through OsiDylp, there's a reasonable chance you're ok. If you have problems, best to open an issue in the coin-or/Dylp repository.

There will be more changes to come, so it's a bit premature to create a stable branch, but this should take care of the vast majority of the code changes.

**Comment by mandeluna** [comment]
Thanks @LouHafer -- I just pulled from master and tried a clean build. The issue is still occurring, but as before, if I change `unavailable` to `isfinite` the project builds successfully and all tests pass. I'll close this issue and re-open in coin-or/DyLP once I've had a chance to investigate further.
